server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # A mágica para o React Router funcionar dentro do Docker
        try_files $uri $uri/ /index.html;
    }
}
